# Use Lean Foundation as the base
FROM node:14.19-bullseye

# Dotnet install
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb

RUN apt-get update; \
    apt-get install -y apt-transport-https && \
    apt-get update && \
    apt-get install -y dotnet-sdk-5.0

# pip
RUN wget -q https://bootstrap.pypa.io/pip/3.6/get-pip.py \
	&& python3 get-pip.py \
	&& pip install --no-cache-dir quantconnect-stubs

# pyright
RUN npm i -g pyright